version: '3'
services:
  redis:
   image: redis:3.0-alpine
   ports:
   - "6379:6379"
   volumes:
   - ./redis.conf:/data/redis.conf
  app:
    restart: always
    build: ./flask_rss
    ports:
    - "9091:9091"
    volumes:
      - ./db:/usr/src/file/db
    depends_on:
      - redis
    command: python app.py
